"""
Unit tests for Drafting Agent.
"""

import pytest
from agents.drafting_agent import DraftingResult, draft_reply


def test_draft_reply_grounding():
    ticket = {
        "id": "T001",
        "subject": "Webhook signature verification keeps failing",
        "body": "No signatures found matching expected signature.",
        "urgency": "high",
    }
    retrieval_res = {
        "retrieved_doc_topics": ["webhook signing secret rotation / raw body middleware ordering"],
        "passages": [
            {
                "doc_topic": "webhook signing secret rotation / raw body middleware ordering",
                "snippet": "Ensure that the raw body is passed directly to stripe.webhooks.constructEvent.",
                "source": "https://docs.stripe.com/webhooks/signatures",
            }
        ],
    }

    result = draft_reply(ticket, retrieval_res)
    assert isinstance(result, DraftingResult)
    assert len(result.draft_reply) > 50
    # Must cite the retrieved topic
    assert "webhook signing secret rotation / raw body middleware ordering".lower() in result.draft_reply.lower()


def test_no_hallucinated_citations():
    ticket = {
        "id": "T002",
        "subject": "Duplicate charges",
        "body": "We retried payment intent creation without idempotency key.",
        "urgency": "high",
    }
    retrieval_res = {
        "retrieved_doc_topics": ["idempotency keys for PaymentIntent creation"],
        "passages": [
            {
                "doc_topic": "idempotency keys for PaymentIntent creation",
                "snippet": "An idempotency key is a unique token generated by the client.",
                "source": "https://docs.stripe.com/api/idempotent_requests",
            }
        ],
    }
    result = draft_reply(ticket, retrieval_res)
    # Check evaluator.py criterion: draft must contain at least one retrieved topic
    retrieved = retrieval_res["retrieved_doc_topics"]
    assert any(r.lower() in result.draft_reply.lower() for r in retrieved)
