"""
Corpus generation script for Stripe-Support-Agent-Dashboard.
Generates 30 paraphrased technical documentation summaries covering all 10 categories
and the 30 ticket topics in labeled_tickets.json.
Unofficial documentation references public Stripe concepts.
"""

import os
import json

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CORPUS_DIR = os.path.join(BASE_DIR, "mcp_servers", "retrieval_server", "docs_corpus")
os.makedirs(CORPUS_DIR, exist_ok=True)

DOCS = [
    {
        "filename": "webhook_signing_secrets.md",
        "topic": "webhook signing secret rotation / raw body middleware ordering",
        "source_url": "https://docs.stripe.com/webhooks/signatures",
        "category": "webhooks",
        "title": "Webhook Signature Verification and Raw Body Middleware",
        "content": """Stripe signs webhook events to verify that requests originate from Stripe and have not been tampered with. To verify signatures, your endpoint must use the raw, unparsed HTTP request body buffer. If JSON parsing middleware (like express.json() or bodyParser.json()) runs before Stripe's signature check, the payload is altered by deserialization, causing signature verification to fail with 'No signatures found matching the expected signature for payload'.

Ensure that the raw body is passed directly to stripe.webhooks.constructEvent(payload, sig, endpointSecret). Additionally, verify that the endpoint secret configured in your application matches the specific endpoint in the Stripe Dashboard (whsec_...). When rotating secrets, configure your application to temporarily accept signatures from both the old and new secrets until all deliveries settle.""",
    },
    {
        "filename": "idempotency_keys.md",
        "topic": "idempotency keys for PaymentIntent creation",
        "source_url": "https://docs.stripe.com/api/idempotent_requests",
        "category": "api_idempotency",
        "title": "Idempotency Keys for PaymentIntent Creation",
        "content": """An idempotency key is a unique token generated by the client that Stripe uses to recognize retries of the exact same request. When creating stateful resources like PaymentIntents, network timeouts or connection drops can leave the client uncertain whether the request succeeded.

By including the Idempotency-Key header (such as a UUIDv4 or order-specific hash like order_4471_attempt_1), retrying the identical POST request will return the previously generated PaymentIntent object instead of creating an accidental duplicate charge. Idempotency keys are cached for 24 hours. For previously created duplicate PaymentIntents that resulted in accidental double charges, developers should retrieve the customer's recent charges and immediately refund the duplicate transaction.""",
    },
    {
        "filename": "stripe_cli_webhooks.md",
        "topic": "Stripe CLI webhook forwarding",
        "source_url": "https://docs.stripe.com/stripe-cli/webhooks",
        "category": "webhooks",
        "title": "Local Webhook Testing with Stripe CLI",
        "content": """The Stripe CLI enables local testing by establishing a secure WebSocket connection to Stripe and forwarding live or test webhook events directly to your local development server without requiring public tunnels like ngrok.

To begin forwarding events, run 'stripe listen --forward-to localhost:4242/webhook'. The CLI will output a local webhook signing secret in the format whsec_test_.... You must update your local environment variables with this temporary CLI secret so signature verification succeeds locally. You can also trigger synthetic events on demand using commands such as 'stripe trigger payment_intent.succeeded' to validate handler logic during development.""",
    },
    {
        "filename": "payout_schedule_holds.md",
        "topic": "payout schedule delays / account verification holds",
        "source_url": "https://docs.stripe.com/connect/payouts",
        "category": "connect_payouts",
        "title": "Connect Payout Delays and Account Verification Holds",
        "content": """On Stripe Connect platforms, funds collected from charges are transferred to connected accounts based on their configured payout schedule (e.g., daily rolling, weekly, or manual). When connected account payouts remain in 'pending' status for extended periods, it frequently signals an underlying compliance review or identity verification hold.

Even if an account initially appeared verified, Stripe periodically requests updated business documentation, identity proofs, or beneficial ownership details. If the account owner has unaddressed requirements in the 'requirements.currently_due' or 'requirements.past_due' fields of their Account object, payouts will be paused. Platform operators can inspect the Account API or Connect Dashboard to review active restrictions and assist the seller with remediation.""",
    },
    {
        "filename": "subscription_billing_cycle_anchor.md",
        "topic": "subscription billing_cycle_anchor and proration behavior",
        "source_url": "https://docs.stripe.com/billing/subscriptions/billing-cycle",
        "category": "billing_subscriptions",
        "title": "Subscription Billing Cycle Anchors and Prorations",
        "content": """The billing_cycle_anchor parameter determines the point in time when recurring subscription periods reset and generate invoices. By default, a subscription's anchor matches the timestamp when it was created.

If you update an existing subscription to change its billing_cycle_anchor (for instance, aligning all customers to the 1st of the month using 'billing_cycle_anchor=now' or an upcoming timestamp), Stripe evaluates proration behavior via the 'proration_behavior' parameter. When set to 'create_prorations', Stripe computes line-item credits for unused time in the previous period and debits for the transitional period leading to the new anchor date. You can preview these calculations prior to confirmation using the Upcoming Invoice API.""",
    },
    {
        "filename": "api_key_exposure_rotation.md",
        "topic": "API key exposure / rotating compromised secret keys",
        "source_url": "https://docs.stripe.com/keys",
        "category": "auth_keys",
        "title": "Compromised API Key Emergency Response and Rotation",
        "content": """If a live secret API key (sk_live_...) is committed to a public repository or exposed, treat it as an active critical security incident. Anyone with access to that key can make unauthorized charges, access customer personal data, and initiate transfers or payouts.

Immediate incident response steps:
1. Immediately navigate to the Stripe Dashboard > Developers > API keys and generate a new secret key.
2. Deploy the new key to your production backend systems.
3. Revoke / delete the compromised secret key from the Dashboard immediately.
4. Review the API request logs in the Dashboard for any unauthorized requests made with the leaked key.
5. Escalate to Stripe Support and your security team if unauthorized funds movement or data exfiltration is suspected.""",
    },
    {
        "filename": "refund_processing_timelines.md",
        "topic": "refund processing timelines by payment method",
        "source_url": "https://docs.stripe.com/refunds",
        "category": "refunds_disputes",
        "title": "Refund Settlement Timelines by Payment Method",
        "content": """When a refund is submitted via the Stripe API or Dashboard and marked as 'succeeded', Stripe immediately submits the refund request to the card networks or underlying payment rail. However, the customer's financial institution requires processing time to post the credit to the account.

For credit and debit cards, refunds typically take between 5 to 10 business days to appear on the customer's statement, depending on the issuing bank's settlement cycle. In rare instances where charges are refunded on the same calendar day, the issuing bank may delete the original authorization entirely rather than posting a distinct credit line item (a reversal). For bank debit methods (ACH, SEPA), refunds may take additional business days to clear.""",
    },
    {
        "filename": "dispute_evidence_submission.md",
        "topic": "dispute evidence submission and deadlines",
        "source_url": "https://docs.stripe.com/disputes/measuring-risk/responding",
        "category": "refunds_disputes",
        "title": "Dispute Evidence Submission Process and Deadlines",
        "content": """When a cardholder disputes a charge with their issuing bank, Stripe creates a Dispute object and immediately deducts the disputed amount plus a network dispute fee from the merchant's account balance.

Merchants have a strict deadline (typically 7 to 21 days, indicated by the 'evidence_details.due_by' timestamp) to submit counter-evidence. For fraudulent claims where delivery took place, effective evidence includes signed proof of delivery, tracking numbers from recognized carriers, matching billing and shipping addresses, IP access logs, and customer communication records. Evidence must be submitted before the deadline via the Dashboard or the Dispute Update API; once the deadline passes, submissions are rejected by card networks.""",
    },
    {
        "filename": "test_vs_live_mode.md",
        "topic": "test vs live mode isolation",
        "source_url": "https://docs.stripe.com/testing",
        "category": "auth_keys",
        "title": "Test Mode vs Live Mode Isolation and Behavior",
        "content": """Stripe provides complete architectural isolation between Test Mode and Live Mode. Test mode requests (authenticated via sk_test_... or pk_test_...) interact solely with simulated card networks and virtual financial accounts. No actual credit card transactions occur, no money moves, and zero real-world financial liability is created.

Objects created in Test Mode (such as customers, products, tokens, and payment intents) do not exist in Live Mode and cannot be referenced by live API requests. You can safely trigger test payments using Stripe's published test card numbers (like 4242 4242 4242 4242) to simulate successful authorizations, insufficient funds, 3DS authentication challenges, and card declines without financial risk.""",
    },
    {
        "filename": "radar_custom_rules.md",
        "topic": "Radar custom rules and allow lists",
        "source_url": "https://docs.stripe.com/radar/rules",
        "category": "radar_fraud",
        "title": "Radar Custom Rules, Risk Evaluation, and Allow Lists",
        "content": """Stripe Radar uses machine learning models trained across the global Stripe network to assign each payment a risk score and risk level (normal, elevated, or highest). By default, Radar blocks payments classified as highest risk.

For legitimate high-value customers who encounter false-positive blocks, merchants can create Radar Allow Lists and custom rules. You can add a customer's email, card fingerprint, or IP address to an allow list. Allow rules (e.g. 'Allow if :email: in @trusted_customers') take precedence over default block rules. However, allow rules do not bypass issuer-level declines or 3D Secure liability shifts. High-value transactions can also be configured to require manual review rather than outright blocking.""",
    },
    {
        "filename": "stripe_tax_calculation.md",
        "topic": "Stripe Tax automatic calculation for digital goods",
        "source_url": "https://docs.stripe.com/tax",
        "category": "tax",
        "title": "Automatic Tax Calculation for Digital Goods with Stripe Tax",
        "content": """Stripe Tax automates sales tax, VAT, and GST calculation, collection, and reporting for global transactions, including cross-border digital goods and SaaS subscriptions. To enable automatic tax calculation, merchants register their active tax obligations in the Stripe Dashboard and set the product's tax_code (e.g., txcd_10000000 for digital software).

When creating Invoices, Subscriptions, or Checkout sessions with 'automatic_tax: {enabled: true}', Stripe Tax calculates the applicable EU VAT or regional tax rate using the customer's billing and IP location evidence. For B2B transactions in the EU, if the customer provides a validated VAT identification number, Stripe Tax automatically applies the reverse charge mechanism (0% VAT).""",
    },
    {
        "filename": "three_ds_flow.md",
        "topic": "3DS authentication flow and confirming PaymentIntents client-side",
        "source_url": "https://docs.stripe.com/payments/3d-secure",
        "category": "payments_charges",
        "title": "3D Secure Authentication and Client-Side Payment Confirmation",
        "content": """Strong Customer Authentication (SCA) mandates 3D Secure (3DS) authentication for European and high-risk card payments. When a customer initiates a payment requiring authentication, the PaymentIntent transitions to the 'requires_action' status.

To complete the flow, your client-side frontend (using Stripe.js or mobile SDKs) must invoke 'stripe.confirmPayment()' or 'stripe.handleNextAction()'. This renders the issuing bank's authentication modal or redirect. Once the user completes the 3DS challenge, the client receives confirmation and the PaymentIntent transitions to 'succeeded' (or 'processing'). If client-side code fails to handle the 'next_action' response or fails to call confirmPayment after challenge completion, the transaction remains trapped in 'requires_action'.""",
    },
    {
        "filename": "custom_pricing_sales.md",
        "topic": "custom pricing / sales contact routing",
        "source_url": "https://docs.stripe.com/pricing",
        "category": "general",
        "title": "Volume Pricing and Sales Routing for High-Scale Accounts",
        "content": """Stripe offers standard pay-as-you-go pricing for transactions, billing, and ancillary services. For rapidly growing businesses and enterprise accounts exceeding standard processing thresholds (typically $100k+ in monthly processing volume), customized volume-based pricing is available through Stripe's Enterprise Sales team.

Custom pricing arrangements can encompass discounted interchange-plus rates, bundled international acquiring discounts, tailored chargeback support, and dedicated technical account management. Account holders interested in evaluating custom pricing contracts should be routed to a sales representative or account executive with details regarding their annualized volume, average ticket size, and geographic mix.""",
    },
    {
        "filename": "trial_end_webhooks.md",
        "topic": "trial_end webhook events and invoice generation timing",
        "source_url": "https://docs.stripe.com/billing/subscriptions/trials",
        "category": "billing_subscriptions",
        "title": "Subscription Trial End Webhooks and Invoice Generation",
        "content": """When a subscription with a trial period reaches its trial_end timestamp, Stripe triggers a series of lifecycle events to transition the subscription from 'trialing' to 'active' and generate the initial recurring invoice.

Approximately three days before a trial expires, Stripe fires 'customer.subscription.trial_will_end' so merchants can notify customers. When the trial formally expires, Stripe fires 'customer.subscription.updated' and creates an invoice. The invoice typically remains in draft status for approximately one hour before being finalized and charged. If customers remain in 'trialing' status after trial expiration, check whether the trial_end timestamp was set in the future or if invoice auto-advance settings were disabled.""",
    },
    {
        "filename": "invoice_pdf_export.md",
        "topic": "invoice PDF export via API vs dashboard",
        "source_url": "https://docs.stripe.com/invoicing/overview",
        "category": "general",
        "title": "Invoice PDF Export Methods via Dashboard and API",
        "content": """Stripe generates downloadable PDF receipts and invoices for all finalized invoice objects. In the Stripe Dashboard under Invoices, merchants can search and export invoice records as CSV reports, but bulk downloading thousands of rendered PDF files directly from the UI is not natively supported in a single click.

To export invoice PDFs in bulk for accounting or archival purposes, developers should utilize the Stripe Invoices API. By iterating through the 'GET /v1/invoices' list endpoint, each invoice object contains an 'invoice_pdf' field with a hosted link directly to the rendered PDF file. An automated script can fetch these URLs and download the PDF documents systematically.""",
    },
    {
        "filename": "connect_application_fees.md",
        "topic": "application fees and fee responsibility in Connect",
        "source_url": "https://docs.stripe.com/connect/direct-charges",
        "category": "connect_payouts",
        "title": "Connect Application Fees and Processing Fee Allocation",
        "content": """In Stripe Connect integrations, the platform can collect an application fee on payments processed through connected accounts by specifying the 'application_fee_amount' parameter on charges or PaymentIntents.

Understanding how Stripe's own payment processing fees interact with application fees depends on the charge type:
- On Direct Charges: The connected account is the merchant of record and pays Stripe's processing fee by default. The platform receives the exact 'application_fee_amount' transferred to the platform balance.
- On Destination Charges: The platform is responsible for Stripe processing fees, refunds, and chargebacks. Stripe fees are deducted from the gross charge before remaining funds are transferred to the connected account, adjusted by the application fee.""",
    },
    {
        "filename": "api_rate_limits_bulk_import.md",
        "topic": "API rate limits and bulk data migration strategies",
        "source_url": "https://docs.stripe.com/rate-limits",
        "category": "api_idempotency",
        "title": "API Rate Limits and Bulk Data Migration Strategies",
        "content": """Stripe enforces rate limits to maintain infrastructure stability and availability. Standard live mode limits are approximately 100 read requests per second and 100 write requests per second under normal operation. When limits are exceeded, the API responds with HTTP status code 429 Too Many Requests.

When performing large-scale customer migrations (such as importing tens of thousands of records):
1. Implement exponential backoff and jitter on all retry attempts when receiving 429 responses.
2. Throttle concurrency across workers so total outbound requests stay well within rate limits.
3. Contact Stripe Support prior to massive scheduled migrations to request temporary rate limit increases or coordinate secure bulk card data transfers through Stripe's PCI-certified migration service.""",
    },
    {
        "filename": "chargeback_monitoring_programs.md",
        "topic": "dispute/chargeback monitoring program consequences",
        "source_url": "https://docs.stripe.com/disputes/monitoring-programs",
        "category": "refunds_disputes",
        "title": "Chargeback Monitoring Programs and Account Consequences",
        "content": """Payment networks (Visa and Mastercard) maintain dispute monitoring programs (such as Visa Dispute Monitoring Program - VDMP and Mastercard Excessive Dispute Program). These programs track a merchant's monthly dispute-to-transaction ratio.

Crossing threshold levels (typically 0.9% dispute ratio and 100 disputes/month for Visa standard tier) results in severe penalties:
- Substantial monthly network fines ($50+ per dispute).
- Increased scrutiny, higher processing reserves, or mandatory remediation plans.
- Risk of account termination or merchant match listing if unaddressed.
Merchants approaching thresholds must immediately deploy fraud prevention measures (Radar rules, mandatory 3DS, early fraud warnings/Verifi/Ethoca alerts) and refund high-risk orders before they turn into disputes.""",
    },
    {
        "filename": "webhook_delivery_ordering.md",
        "topic": "webhook delivery ordering guarantees (or lack thereof)",
        "source_url": "https://docs.stripe.com/webhooks",
        "category": "webhooks",
        "title": "Webhook Delivery Ordering and Concurrency Guarantees",
        "content": """Stripe does not guarantee that webhook events will be delivered in the exact chronological order in which they were generated. Because webhook deliveries are distributed across concurrent asynchronous workers and subject to network retries, an event like 'invoice.paid' can occasionally reach your server before 'invoice.created'.

Your webhook ingestion architecture must be designed defensively:
1. Do not assume strict event sequencing in internal state machines.
2. Use the 'created' timestamp on the enclosed Stripe object or query the Stripe API directly to fetch the authoritative, latest object state upon event receipt.
3. Make all event handlers idempotent by storing processed event IDs (evt_...) to prevent duplicate processing on retries.""",
    },
    {
        "filename": "account_closure_subscriptions.md",
        "topic": "account closure and subscription/data handling implications",
        "source_url": "https://docs.stripe.com/account/close",
        "category": "billing_subscriptions",
        "title": "Account Closure Implications for Active Subscriptions and Data",
        "content": """Closing a Stripe account is an irreversible action that terminates payment processing capabilities. When an account is closed:
- All active recurring subscriptions are canceled and will not generate future invoices or automatic charges.
- Any pending payouts are settled according to standard payout schedules, provided no outstanding negative balances or compliance holds exist.
- Access to the Dashboard transitions to read-only historical reporting mode.

Before closing an account, merchants should explicitly export customer data, invoices, and accounting reports. If transitioning customers to another payment provider, merchants should request a secure card data migration prior to closure, as card details cannot be exported or migrated after an account is formally closed.""",
    },
    {
        "filename": "payment_request_wallets.md",
        "topic": "Payment Request Button / wallet support overview",
        "source_url": "https://docs.stripe.com/elements/payment-request-button",
        "category": "general",
        "title": "Payment Request Button and Digital Wallet Support (Apple & Google Pay)",
        "content": """Stripe provides out-of-the-box support for digital wallet payment methods, including Apple Pay and Google Pay, via the Payment Request Button and Payment Element. No separate merchant accounts or vendor agreements with Apple or Google are required.

To enable Apple Pay and Google Pay:
1. In the Stripe Dashboard under Payment Methods, enable Apple Pay and Google Pay.
2. For web implementations using Apple Pay, register and verify your domain name with Apple via the Stripe Dashboard or API.
3. Integrate the Payment Request Button in your checkout frontend; Stripe.js automatically detects device and browser compatibility and displays the appropriate Apple Pay or Google Pay button natively.""",
    },
    {
        "filename": "charge_refund_fields.md",
        "topic": "Charge object refund fields (amount_refunded vs amount)",
        "source_url": "https://docs.stripe.com/api/charges/object",
        "category": "refunds_disputes",
        "title": "Charge Object Refund Fields: amount_refunded vs amount",
        "content": """When inspecting a Charge object following a partial or full refund, developers must distinguish between different financial attributes:
- 'amount': Represents the original total gross amount charged in the smallest currency unit (e.g., 10000 for $100.00). This field remains constant throughout the charge lifecycle.
- 'amount_refunded': Tracks the cumulative total amount that has been refunded to date. After a $20.00 refund on a $100.00 charge, 'amount' remains 10000 while 'amount_refunded' updates to 2000.
- 'refunded': A boolean flag that only flips to 'true' once the entire charge has been refunded ('amount_refunded == amount').

To compute remaining refundable funds, subtract 'amount_refunded' from 'amount'.""",
    },
    {
        "filename": "account_security_incident_2fa.md",
        "topic": "account security incident response / 2FA enforcement",
        "source_url": "https://docs.stripe.com/security",
        "category": "auth_keys",
        "title": "Account Security Incident Response and 2FA Enforcement",
        "content": """Suspected unauthorized access to a Stripe account constitutes a critical security incident. If an unrecognized login or suspicious IP address is identified in the account activity log, take immediate protective action:
1. Change account passwords immediately and invalidate all active user sessions across all team members.
2. Enforce Two-Factor Authentication (2FA / MFA) across the entire Stripe account team in Dashboard settings.
3. Review team member roles and revoke permissions from any unfamiliar email addresses.
4. Inspect API keys, restricted keys, and webhook endpoints to verify no unauthorized credentials or endpoints were added.
5. Review recent bank account modifications and payout destinations to prevent funds redirection.
6. Report the incident immediately to Stripe Support and security operations.""",
    },
    {
        "filename": "provincial_tax_rates_canada.md",
        "topic": "provincial tax rates and address validation for Stripe Tax",
        "source_url": "https://docs.stripe.com/tax/canada",
        "category": "tax",
        "title": "Canadian Provincial Tax Rates (GST/HST/PST) and Address Validation",
        "content": """In Canada, indirect tax calculation depends heavily on the specific province or territory of the customer:
- Participating provinces (like Ontario, Nova Scotia, New Brunswick) impose a combined Harmonized Sales Tax (HST) (e.g. 13% in Ontario).
- Other provinces impose separate federal Goods and Services Tax (GST, 5%) plus Provincial Sales Tax (PST) or Quebec Sales Tax (QST).

If Stripe Tax calculated 5% GST instead of 13% HST for an Ontario customer, verify two factors:
1. Ensure your account has registered active tax obligations in Ontario under Stripe Tax settings. If registration is only enabled at the federal Canadian level, Stripe Tax collects solely federal GST.
2. Ensure the customer's shipping/billing postal code is validated as an Ontario address; incomplete postal codes default to federal rates.""",
    },
    {
        "filename": "api_log_retention.md",
        "topic": "API request log retention period",
        "source_url": "https://docs.stripe.com/dashboard#logs",
        "category": "general",
        "title": "Stripe API Request Log Retention Policy",
        "content": """Stripe retains detailed API request and response logs in the Stripe Dashboard for 30 calendar days. These logs capture HTTP headers, request payloads, response bodies, and latency metrics for debugging purposes.

Logs older than 30 days are automatically expunged from the interactive Dashboard and cannot be retrieved retroactively. For long-term audit compliance, debugging historical transactions, or internal data warehousing:
- Stream webhook event payloads to an internal database or log management platform (like Datadog, BigQuery, or CloudWatch).
- Maintain an internal event ledger recording key transaction IDs, request parameters, and status responses permanently.""",
    },
    {
        "filename": "radar_rules_country_tuning.md",
        "topic": "Radar risk rules by country and custom rule tuning",
        "source_url": "https://docs.stripe.com/radar/rules/country",
        "category": "radar_fraud",
        "title": "Radar Risk Rules by Geographic Region and Custom Tuning",
        "content": """Stripe Radar's default machine learning models evaluate geographic factors, including card issuing country, IP geolocation, and international dispute patterns. In specific regions with higher historical fraud baselines (such as certain emerging markets), default risk scoring can trigger elevated false-positive block rates for legitimate domestic or regional merchants.

To tune Radar rules for legitimate international operations:
1. Add custom allow or 3DS rules in Radar: 'Request 3D Secure if :ip_country: == "NG" and :risk_level: == "elevated"'. This shifts chargeback liability to the issuer while permitting genuine transactions.
2. Whitelist known corporate customers or verified payment methods.
3. Review blocked payments in the Dashboard to provide feedback to Radar ML models by marking false positives as safe.""",
    },
    {
        "filename": "api_versioning_webhooks.md",
        "topic": "API versioning and webhook endpoint version pinning",
        "source_url": "https://docs.stripe.com/api/versioning",
        "category": "api_idempotency",
        "title": "API Versioning and Webhook Endpoint Version Pinning",
        "content": """Stripe pins API versions at both the account level and the webhook endpoint level. When you upgrade your account's default API version in the Dashboard or test with the 'Stripe-Version' header, existing webhook endpoints are NOT automatically modified or broken.

Each webhook endpoint is permanently pinned to the API version that was active when the endpoint was created. Upgrading your account API version will not change event schemas sent to that webhook endpoint. If you wish to migrate a webhook endpoint to a newer schema version, you can test the new version on a secondary endpoint or explicitly update the endpoint's pinned version in Dashboard > Webhooks after updating your ingestion code.""",
    },
    {
        "filename": "connect_identity_verification.md",
        "topic": "identity verification failures in Connect onboarding",
        "source_url": "https://docs.stripe.com/connect/identity-verification",
        "category": "connect_payouts",
        "title": "Identity Verification and SSN Rejection in Connect Onboarding",
        "content": """During Stripe Connect onboarding, sellers must complete identity verification (Know Your Customer / KYC). When a Social Security Number (SSN) or national ID is repeatedly rejected:
1. Verification discrepancies typically stem from minor mismatches between the provided legal name, date of birth, and home address against credit bureau and government records.
2. Recent legal name changes, moves, or typos in the legal name field will cause automated matching algorithms to reject the input.
3. If automated verification fails repeatedly, Stripe allows users to upload government photo identification (driver's license or passport) and proof of address. Platform admins can inspect the Account API 'requirements.disabled_reason' field and share a generated verification update link with the seller.""",
    },
    {
        "filename": "api_version_changelog.md",
        "topic": "API version changelog / upgrade guide",
        "source_url": "https://docs.stripe.com/upgrades",
        "category": "general",
        "title": "Stripe API Version Changelog and Upgrade Guides",
        "content": """Stripe publishes a comprehensive API Changelog documenting all backward-incompatible breaking changes, deprecations, and schema enhancements between releases.

Before upgrading your account's default API version:
1. Review the API Changelog for every release between your current version and the target version.
2. Note changes to response properties, renamed parameters, and altered webhook payloads.
3. Test your integration incrementally using the 'Stripe-Version' request header in your staging environment to execute requests against the new API version without altering production default behavior.
4. Upgrade your default account version in the Stripe Dashboard only after testing confirms full compatibility.""",
    },
    {
        "filename": "decline_codes_invoice_failures.md",
        "topic": "decline codes and reading detailed failure reasons on invoices",
        "source_url": "https://docs.stripe.com/declines/codes",
        "category": "billing_subscriptions",
        "title": "Card Decline Codes and Investigating Recurring Invoice Failures",
        "content": """When an automatic recurring subscription invoice fails with a generic 'card_declined' error, the customer's issuing bank has refused the charge. While the high-level error may state 'card_declined', Stripe receives specific decline codes from the card network.

To find the exact decline reason:
1. Inspect the Invoice object and locate the associated PaymentIntent ('invoice.payment_intent').
2. In the PaymentIntent, look at the latest charge or 'last_payment_error.decline_code'.
3. Common decline codes include 'insufficient_funds', 'do_not_honor', 'expired_card', 'transaction_not_allowed', or 'suspected_fraud'.
4. For codes like 'do_not_honor' or 'generic_decline', banks refuse the transaction due to automated security rules on recurring charges; the cardholder must contact their issuing bank directly to authorize Stripe charges.""",
    },
]

def main():
    print(f"Generating {len(DOCS)} documentation summaries in {CORPUS_DIR}...")
    created = []
    for doc in DOCS:
        filepath = os.path.join(CORPUS_DIR, doc["filename"])
        frontmatter = f"""---
topic: "{doc['topic']}"
source_url: "{doc['source_url']}"
category: "{doc['category']}"
---
# {doc['title']}

{doc['content'].strip()}
"""
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(frontmatter)
        created.append(doc["filename"])
    print(f"Successfully generated {len(created)} docs in corpus.")

if __name__ == "__main__":
    main()
